### ISSUE TITLE
-equivalenceAlgorithms Select Error

### ISSUE THREAD

**Issue by 5angjun** [assist-project/dtls-fuzzer#113]
![image](https://github.com/assist-project/dtls-fuzzer/assets/76202024/9888ae9b-f49b-4231-bbe7-156b60754ca6)

Hi there.

I'm someone who really interested in your project.

But i think there is bit a error in README.md.

When i try to run handshake test, that would be error in parameter.

How should i do?

I have a trouble because i can't known this whole source code.

Can you give some ideas?

Thanks.

**Comment by kostis** [comment]
Hi @5angjun and thanks for your interest in DTLS-Fuzzer!

The README file clearly needs some care and affection (i.e. a major update) because it corresponds to version of the tool before some major updates to its code base took place.  So, some examples there may not work as described anymore.

Still, in this particular case the parsing problem you experienced was caused by some extraneous trailing white space characters in the  `args/openssl/learn_openssl_server_psk` file.  A commit I just pushed fixes that issue.  Please try it again and see whether things now work or fail at some other point for you and let us know.

**Comment by 5angjun** [comment]
Thanks for suggesting the solution. But the following error occurred:
![image](https://github.com/assist-project/dtls-fuzzer/assets/76202024/c042d57f-c86d-4fee-a4b1-9a4622430659)

Can you test openssl in readme.md in a completely clean state?
I seems unstable in current version. but i can execute it in usenix20 branch.

**Comment by 5angjun** [comment]
I can run without `-queries` options. But i don't know that it ensure the perfect model learning. 
Because it doesn't end until now. ( I start learning before 2hours ago...)

Can you give me a some solution?
![image](https://github.com/assist-project/dtls-fuzzer/assets/76202024/4d095fb1-4ca7-40e6-904e-8602eb7c30fb)

**Comment by kostis** [comment]
Great that you are achieving some progress! 

Quite often, when dealing with (complex) protocol implementations, there is no such thing as _perfect_ model learning; the learning is usually approximate, for a number of reasons, but the learned model (the last `hypN.dot` file produced) is quite accurate and useful.

Instead of using a fixed number of queries (the `-queries` option you have tried) to force learning to terminate, you can try to use a fixed number of rounds (`-rounds` option, i.e. the `N` above) or simply interrupt the learning process after some time (e.g. 10 hours) and use the last hypothesis which has been generated.

**Comment by 5angjun** [comment]
Thanks for helping me.

I finally got the hypothesis through this.

Really thanks.

![image](https://github.com/assist-project/dtls-fuzzer/assets/76202024/d4e32826-9f1e-4baf-afdc-ec6f6a3b4cc6)

**Comment by actyp** [comment]
There has been a point, when `ProtocolState-Fuzzer` was integrated in this repo.

The `usenix20-artifact` branch is before the integration and the `master` branch is after the integration, so they have some significant changes.

The `-queries` parameter, for instance, was renamed after the integration to `-eqvQueries` (or the full name `-equivalenceQueryBound`), as it refers to the maximum number of queries of certain equivalence algorithms. This is specified in the `ProtocolState-Fuzzer` repo.

That is why, an error was raised if you used the `-queries` parameter in the `main` branch. If you want, you can use `-eqvQueries` instead.
